populate_keyring() {
    keyid=$(head -n 1 usr/share/pacman/keyrings/qubesos-devel-trusted|cut -f 1 -d :)
    if usr/bin/pacman-key -l "$keyid" >/dev/null 2>&1; then
        # already done
        return
    fi
    if [ "$(df --output=fstype etc/pacman.d/gnupg/private-keys-v1.d|tail -n 1)" = "ramfs" ]; then
        # if pacman's keyring is volatile, generate new one (note: private key
        # won't survive anyway)
        usr/bin/pacman-key --init
        usr/bin/pacman-key --populate
    else
        # otherwise, import just new keys
        usr/bin/pacman-key --populate qubesos-devel
    fi
}

post_upgrade() {
    if usr/bin/pacman-key -l >/dev/null 2>&1; then
        populate_keyring
    fi
}

post_install() {
    if [ -x usr/bin/pacman-key ]; then
        post_upgrade "$1"
    fi
}
