post_upgrade() {
    if usr/bin/pacman-key -l >/dev/null 2>&1; then
        usr/bin/pacman-key --populate qubesos-vm
    fi
    release=$(echo "$1" | cut -d '.' -f 1,2)

    if ! [ -h /etc/pacman.d/90-qubes-${release}-current.conf ] ; then
        ln -s qubes-${release}-current.conf.disabled /etc/pacman.d/90-qubes-${release}-current.conf
    fi

}

post_install() {
    if [ -x usr/bin/pacman-key ]; then
        post_upgrade "$1"
    fi
}
